name: Node.js

on:
  push:
    branches-ignore:
    - gh-pages

  pull_request:
    branches-ignore:
    - gh-pages


jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install NPM dependencies
      run: npm ci

    - name: Run tests
      run: npm run test:prod


  deploy-gh-pages:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production'
    needs: tests

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install NPM dependencies
      run: npm ci

    - name: Build for production
      run: |
        npm run build:prod -- --output-path dist
        cp dist/index.html dist/404.html

    - name: Deploy to Github Pages 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
        CLEAN: true
